
executor: slurm
jobs: 75

latency-wait: 100
rerun-incomplete: True
printshellcmds: True
use-conda: True
retries: 1
remote-job-local-storage-prefix: "/localhd/$SLURM_JOB_ID"

__default__:
  job-name: "{rule}"
  mem: "20G"
  time: "20:00:00"
  output: "logs/%x-%j.out"

#rule specific resources go below
set-resources:
    myrule:
        mem: 500MB
